{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "task-system.fullname" . }}-postgres
  labels:
    {{- include "task-system.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "task-system.name" . }}-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "task-system.name" . }}-postgres
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      {{- if or .Values.serviceAccount.create .Values.serviceAccount.name }}
      serviceAccountName: {{ if .Values.serviceAccount.name }}{{ .Values.serviceAccount.name }}{{ else }}{{ include "task-system.fullname" . }}{{ end }}
      {{- end }}
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}{{ if .Values.postgres.tag }}:{{ .Values.postgres.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.postgres.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.database }}"
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          {{- if .Values.postgres.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "task-system.fullname" . }}-postgres-data
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-system.fullname" . }}-postgres
  labels:
    {{- include "task-system.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "task-system.name" . }}-postgres
{{- end }}
