apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: task-system

data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS tasks (
      id UUID PRIMARY KEY,
      task TEXT NOT NULL,
      status TEXT NOT NULL
    );