imagePullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

nodeSelector: {}
tolerations: []
affinity: {}

resources: {}

postgres:
  enabled: true
  image: postgres:15
  tag: ""
  pullPolicy: IfNotPresent
  replicaCount: 1
  user: dev
  password: dev
  database: tasks
  service:
    port: 5432
  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""

redis:
  enabled: true
  image: redis:7
  pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    port: 6379

api:
  enabled: true
  image: ayolannister/task-operatingsystem-api
  tag: latest
  pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5000
  env:
    DB_HOST: postgres
    DB_USER: dev
    DB_PASSWORD: dev
    DB_NAME: tasks
    REDIS_HOST: redis

frontend:
  enabled: true
  image: ayolannister/task-operatingsystem-frontend
  tag: latest
  pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000
  env:
    API_URL: /api

worker:
  enabled: true
  image: ayolannister/task-operatingsystem-worker
  tag: latest
  pullPolicy: IfNotPresent
  replicaCount: 1
  env:
    DB_HOST: postgres
    DB_USER: dev
    DB_PASSWORD: dev
    DB_NAME: tasks
    REDIS_HOST: redis

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
