name: AKS CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: taskregistry1
  ACR_LOGIN_SERVER: taskregistry1.azurecr.io
  RESOURCE_GROUP: task-resource-group
  AKS_CLUSTER:  demo

jobs:
  terraform-build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

   
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: ./aks-infra
      run: terraform init

    - name: Terraform Validate
      working-directory: ./aks-infra
      run: terraform validate

    - name: Terraform Plan
      working-directory: ./aks-infra
      run: terraform plan

    
    - name: Terraform Apply
      working-directory: ./aks-infra
      run: terraform apply -auto-approve

   
    - name: Get AKS Credentials
      run: |
        az aks get-credentials \
          --resource-group $RESOURCE_GROUP \
          --name $AKS_CLUSTER \
          --overwrite-existing

    
    - name: ACR Login
      run: az acr login --name $ACR_NAME

    
    - name: Build API Image
      run: |
        docker build \
          -t $ACR_LOGIN_SERVER/api:${{ github.sha }} \
          ./api

    - name: Build Worker Image
      run: |
        docker build \
          -t $ACR_LOGIN_SERVER/worker:${{ github.sha }} \
          ./worker

    - name: Build Frontend Image
      run: |
        docker build \
          -t $ACR_LOGIN_SERVER/frontend:${{ github.sha }} \
          ./frontend

   
    - name: Push API Image
      run: docker push $ACR_LOGIN_SERVER/api:${{ github.sha }}

    - name: Push Worker Image
      run: docker push $ACR_LOGIN_SERVER/worker:${{ github.sha }}

    - name: Push Frontend Image
      run: docker push $ACR_LOGIN_SERVER/frontend:${{ github.sha }}

    
    - name: Update API Deployment
      run: |
        kubectl set image deployment/api \
          api=$ACR_LOGIN_SERVER/api:${{ github.sha }} \
          -n task-system

    - name: Update Worker Deployment
      run: |
        kubectl set image deployment/worker \
          worker=$ACR_LOGIN_SERVER/worker:${{ github.sha }} \
          -n task-system

    - name: Update Frontend Deployment
      run: |
        kubectl set image deployment/frontend \
          frontend=$ACR_LOGIN_SERVER/frontend:${{ github.sha }} \
          -n task-system

    
    - name: Verify API Rollout
      run: |
        kubectl rollout status deployment/api -n task-system

    - name: Verify Worker Rollout
      run: |
        kubectl rollout status deployment/worker -n task-system

    - name: Verify Frontend Rollout
      run: |
        kubectl rollout status deployment/frontend -n task-system

    
    # Show Cluster State
    
    - name: Kubernetes Status
      run: |
        kubectl get pods -n task-system
        kubectl get svc -n task-system
        kubectl get ingress -n task-system